require('settings')
require('mappings')
require('packer-config')
require('nvim-tree-config')
require('lsp-config')
require('telescope-config')
require('comment-nvim-config')
require('lualine-config')
